
USER_JUNIPER_DIR = "/root/machinegate/juniperapi/"

USER_VAR_POLICIES = USER_JUNIPER_DIR + "var/policies/"

USER_DATABASES_DIR = USER_JUNIPER_DIR + "databases/"

USER_NAME = "j1002391"

USER_PASSWORD = "Start@1jhyo"

ENCAP_PASSWORD = "Adfakladjfqern@sdfjlaf1!"

PARAMIKO_DEFAULT_TIMEWAIT = 5

RUNSERVER_PORT = '8080'

POLICY_FILE_MAX = 300
