from django.shortcuts import render

# Create your views here.
from juniperapi.juniperviews.juniper_devicelist import juniper_devicelist
from juniperapi.juniperviews.juniper_showroute import juniper_showroute
from juniperapi.juniperviews.juniper_exportpolicy import juniper_exportpolicy
from juniperapi.juniperviews.juniper_cachingpolicy import juniper_cachingpolicy
from juniperapi.juniperviews.juniper_cachingnat import juniper_cachingnat
from juniperapi.juniperviews.juniper_searchzonefromroute import juniper_searchzonefromroute
from juniperapi.juniperviews.juniper_searchpolicy import juniper_searchpolicy
