
USER_F5_DIR = "/root/machinegate/f5restapi/"

USER_DATABASES_DIR = USER_F5_DIR + "databases/"

USER_VAR_STATS = USER_F5_DIR + "var/stats/"

USER_NAME = "admin"

USER_PASSWORD = "Skplanet8!"

ENCAP_PASSWORD = "Adfakladjfqern@sdfjlaf1!"

LOG_FILE = USER_F5_DIR + "access.log"

THREAD_TIMEOUT = 1

STATS_VIEWER_COUNT = 5

STATS_SAVEDDATA_MULTI = 31

STATS_TOP_COUNT = 10

RUNSERVER_PORT = '8080'

ROLLBAK_INTERVAL = 5
